### ISSUE TITLE
Camera flipping on Mobile devices

### ISSUE THREAD

**Issue by thehappycoder** [versatica/mediasoup-client#14] opened 2018-01-04 05:58 UTC
Moving https://github.com/versatica/mediasoup-demo/issues/16 to this repo.

Currently there is no way to flip a camera on a mobile device using mediasoup-client. I tried mediasoup-demo, and it didn't work. The current workaround is to stop the tracks both on mediaStream and videoProducer:

Typescript example:
```
export const switchCamera = async (
  videoDevicesCycle: Iterator<MediaDeviceInfo>,
  videoStream: MediaStream,
  videoProducer: any
): Promise<MediaStream> => {
  const videoDevice = videoDevicesCycle.next().value

  videoStream!.getVideoTracks()[0].stop()
  videoProducer.track.stop()

  videoStream = await getStream(
    config.videoMediaStreamConstraints(videoDevice!.deviceId)
  )

  await videoProducer.replaceTrack(videoStream.getVideoTracks()[0])

  return videoStream
}
```

**Comment by ibc** [comment] 2018-01-04 09:41
Copied from the original issue:

```
console.log('Creating trackended and close event handlers')

  videoProducer.on('trackended', () => {
    console.log('!!!!!!!!!!!!!!!!!', 'trackended')
  })

  videoProducer.on('close', () => {
    console.log('!!!!!!!!!!!!!!!!!', 'close')
  })
```

> Got `Creating trackended and close event handlers` but didn't get the other console logs.

> I think this https://bugs.chromium.org/p/chromium/issues/detail?id=752913 explains why it happens.

**Comment by ibc** [comment] 2018-01-04 09:45
Yes, calling `track.stop()` should not trigger "ended" event in the track, but it does. So, because of it, the `Producer` should call its `close()` method. I just cannot understand how `close()` is not called (given that the `trackended` event is fired in the Producer).

**Comment by thehappycoder** [comment] 2018-01-15 01:53
track.stop() seems to be triggering `onended` in Linux Chrome, and, therefore, closing the producer https://github.com/versatica/mediasoup-client/blob/master/lib/Producer.js#L575

But it doesn't trigger `onended` in Android Chrome at least.

**Comment by wyqydsyq** [comment] 2018-01-15 02:04
Calling `videoProducer.track.stop()` before `videoProducer.replaceTrack(replacementStream.getVideoTracks()[0])` on desktop (Chrome `61.0.3163.79`) throws an error:
```
Error: Producer closed
```
Yet not calling it on mobile will prevent you switching to a device more than once as it seems the device lock is not released without calling this.

I'm using a work around in our switch camera function:
```
  if (isMobile) {
    videoProducer.track.stop()
  }

  videoProducer.replaceTrack(replacementStream.getVideoTracks()[0])
```
Which seems to work fine in both use cases

**Comment by ibc** [comment] 2018-01-15 10:30
Regardless Chrome's bug, that's the expected behavior: if the handled cloned track is stopped the Producer is closed (so unusable). I'm about change that behavior so the track's "ended" event won't close the Producer but just emit "trackended" event in the Producer. Then it's up to the app whether to close the Producer or not.

**Comment by ibc** [comment] 2018-01-15 10:32
The thing is: why do you need to stop the interna cloned track before calling replaceTrack()? If that's needed that's due to a bug somewhere else in libwebrtc or the browser WebRTC engine and should be reported in the corresponding project.

**Comment by thehappycoder** [comment] 2018-01-15 10:47
Phones typically don't allow opening both the front and back camera at the same time. I am not sure if it's a bug. It's been like that for long time, and I think we have to make workarounds as it is almost impossible to persuade both Google and Apple to change this.

**Comment by ibc** [comment] 2018-01-15 11:43
This is done in the `react-native` branch. Please use it as we are doing several improvements into it while playing with React-Native.

**Comment by thehappycoder** [comment] 2018-01-22 04:39
Can you release it in `2.0.7`? It turns out that on some phones, track.onended is called too.

**Comment by ibc** [comment] 2018-01-22 19:40
2.0.7 published and API documentation updated.

**Closed by ibc** 2018-01-22 19:40 UTC
