### ISSUE TITLE
Frequent joining and quitting meetings will cause the memory of chrome browser to continue to grow

### ISSUE THREAD

**Issue by bingofree2015** [versatica/mediasoup-client#236] opened 2023-01-09 07:43 UTC
I used two machines to open the chrome browser and join the same conference room. One machine (Machine A) observed the changes in memory, and the other machine (Machine B) frequently joined and exited the conference through automated testing tools, with a frequency of 1 second. This lasted about 5 hours

The browser memory of machine A continues to grow from 113.347K to 497.890K. If it lasts for about 24 hours, the browser memory may grow to more than 1G, causing the browser to crash.

Code snippet:

Step 1:

const consumer = await this._ recvTransport.consume(

{

id,

producerId,

kind,

rtpParameters,

appData : { ...appData, peerId } // Trick.

});

Step 2:

consumer.close();

Step 3:

const consumer = await this._ recvTransport.consume(

{

id,

producerId,

kind,

rtpParameters,

appData : { ...appData, peerId } // Trick.

});

Step 4:

consumer.close();

....

**Comment by ibc** [comment] 2023-01-09 09:23
Is such a snippet code based on mediasoup-demo client side code? If so, I don't think it's cleaning up all the required stuff when closing a consumer so the leak is due to the demo app itself. I cannot consider this report valid unless proper reproducing code is provided.

**Comment by bingofree2015** [comment] 2023-01-10 01:50
Hello, this time is based on the official demo address https://v3demo.mediasoup.org/ As a test environment, two physical machines, machine A and machine B, are used. Machine A joins a conference room through Chrome browser, for example:

https://v3demo.mediasoup.org/?roomId=9012 Then machine B continuously joins and exits the meeting that machine A joins through the browser. After 5 hours, it is found that the browser memory of machine A will continue to grow from the initial 118.54M to about 670.724M, and then machine B stops joining and quitting the meeting

Close the browser and find that the memory of machine A has remained at about 670M and cannot be released.
![QQ图片20230110094939](https://user-images.githubusercontent.com/14192128/211443528-844c8c7a-7fa4-4ab0-b26d-0d8d69996f5b.png)

**Comment by ibc** [comment] 2023-01-11 11:44
Closing since this is duplicate of https://github.com/versatica/mediasoup-client/issues/237 (or the other way around) and rationale was given in there:

https://github.com/versatica/mediasoup-client/issues/237#issuecomment-1378626324

**Closed as completed by ibc** 2023-01-11 11:44 UTC
Labels: bug
