### ISSUE TITLE
Error Failed to execute 'createOffer' on 'RTCPeerConnection

### ISSUE THREAD

**Issue by geongun20** [versatica/mediasoup-client#144] opened 2020-11-19 03:37 UTC
### Your environment

- Operating system: Catalina 10.15.7
- Browser version: chrome Version 87.0.4280.67 (Official Build) (x86_64)
- mediasoup version: 3.6.16
- mediasoup-client version: 3.6.12

### Issue description
1. produce screen sharing with audio using getDisplayMedia.
2. close created producers.
3. produce screen sharing with audio again
4. then the error occurs and producing failed

```
Failed to produce DOMException: Failed to execute 'createOffer' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Unknown transceiver.
```

- This error occures only when selecting chrome tab with share video.

![image](https://user-images.githubusercontent.com/43872798/99617896-a008eb00-2a63-11eb-8337-8154c68b65cc.png)

- And It didn't occur in chrome version 86.0.

**Comment by newsiberian** [comment] 2020-11-19 09:19
Hi, @ibc, I have a stable case for this bug. It appears when I rapidly turn on / off camera and mic simultaneously few times

and it throws an exception `Failed to execute 'createOffer' on 'RTCPeerConnection': Session error code: ERROR_CONTENT. Session error description: Unknown transceiver.`

And I also confirm that this bug was introduced by Chromium 87

**Comment by ibc** [comment] 2020-11-19 14:11
Please don't mention me in issues, I'm not the only one that can handle this (others, including non mediasoup maintainers) may also help with PRs).

I'll take a look when I get some spare time.

**Comment by ibc** [comment] 2020-11-19 14:48
Ok, I've found a very simple way to reproduce this using the mediasoup demo with Chrome 87:

1. Enable mic and webcam.
2. Close the webcam (in console: `CC.disableWebcam()`).
3. Close the mic (in console: `CC.disableMic()`).

```
mediasoup-client:WARN:Transport producer.close() failed:DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Unknown transceiver
```

This is definitely related to something that has changed in Chrome M87.

**Comment by fippo** [comment] 2020-11-19 14:51
Can you turn that into a fiddle? Paging @alvestrand

**Comment by ibc** [comment] 2020-11-19 14:53
I'll try. However the thing is that we close transceivers by setting remote port to 0. This has worked perfectly until M87. Will dig into it.

**Comment by ibc** [comment] 2020-11-19 15:16
Wait, this is a bug in libwebrtc on M87, the error happens here:

```javascript
		const offer = await this._pc.createOffer();

		logger.debug(
			'stopSending() | calling pc.setLocalDescription() [offer:%o]',
			offer);

		await this._pc.setLocalDescription(offer);  // <--- HERE
```

And we know the rule: if Chrome fails to consume what it has generated, that's a bug in Chrome.

**Comment by ibc** [comment] 2020-11-19 15:32
The scenario is:

- We are sending audio and video (and have also a m= section for DataChannel).
- We stop sending webcam.
- Then we stop sending audio. And here it when we get the error.

When it comes to stop sending audio, we do this in the audio transceiver:

```ts
transceiver.sender.replaceTrack(null);
pc.removeTrack(transceiver.sender);
```

**However** the bug happens even if we don't call those two methods.

And this is the local SDP **before** calling `createOffer()`:

```
v=0
o=- 2568895024905517701 5 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1 2
a=msid-semantic: WMS 4b887cad-36bc-43a7-bc11-b1d7b43b3e4d
m=audio 54719 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.1.34
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:111704799 1 udp 2122260223 192.168.1.34 54719 typ host generation 0 network-id 1 network-cost 10
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d b4d789c2-2c83-45a4-ab95-a56190a858a3
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:276845568 cname:AEPySZBUk0uZoSU/
a=ssrc:276845568 msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d b4d789c2-2c83-45a4-ab95-a56190a858a3
a=ssrc:276845568 mslabel:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d
a=ssrc:276845568 label:b4d789c2-2c83-45a4-ab95-a56190a858a3
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:1
a=sctp-port:5000
a=max-message-size:262144
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 118 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:2
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d e66bb93c-1fb4-49f8-bcaa-639b243c2ca9
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:118 rtx/90000
a=fmtp:118 apt=123
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
a=rid:r0 send
a=rid:r1 send
a=rid:r2 send
a=simulcast:send r0;r1;r2
```

And this is the local SDP given by `createOffer()`:

```
v=0
o=- 2568895024905517701 6 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS 4b887cad-36bc-43a7-bc11-b1d7b43b3e4d
m=audio 54719 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 192.168.1.34
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:111704799 1 udp 2122260223 192.168.1.34 54719 typ host generation 0 network-id 1 network-cost 10
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d b4d789c2-2c83-45a4-ab95-a56190a858a3
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:276845568 cname:AEPySZBUk0uZoSU/
a=ssrc:276845568 msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d b4d789c2-2c83-45a4-ab95-a56190a858a3
a=ssrc:276845568 mslabel:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d
a=ssrc:276845568 label:b4d789c2-2c83-45a4-ab95-a56190a858a3
m=application 9 UDP/DTLS/SCTP webrtc-datachannel
c=IN IP4 0.0.0.0
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:1
a=sctp-port:5000
a=max-message-size:262144
m=video 0 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 118 114 115 116
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:Grj8
a=ice-pwd:3y+onayy19qUPDGsRlI+gSUs
a=ice-options:trickle
a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
a=setup:actpass
a=mid:2
a=inactive
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:98 VP9/90000
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
a=fmtp:98 profile-id=0
a=rtpmap:99 rtx/90000
a=fmtp:99 apt=98
a=rtpmap:100 VP9/90000
a=rtcp-fb:100 goog-remb
a=rtcp-fb:100 transport-cc
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=fmtp:100 profile-id=2
a=rtpmap:101 rtx/90000
a=fmtp:101 apt=100
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:119 rtx/90000
a=fmtp:119 apt=124
a=rtpmap:123 H264/90000
a=rtcp-fb:123 goog-remb
a=rtcp-fb:123 transport-cc
a=rtcp-fb:123 ccm fir
a=rtcp-fb:123 nack
a=rtcp-fb:123 nack pli
a=fmtp:123 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=rtpmap:118 rtx/90000
a=fmtp:118 apt=123
a=rtpmap:114 red/90000
a=rtpmap:115 rtx/90000
a=fmtp:115 apt=114
a=rtpmap:116 ulpfec/90000
```

And it happens that calling `pc.setLocalDescription()` with this offer fails with:

```
DOMException: Failed to execute 'setLocalDescription' on 'RTCPeerConnection': Failed to set local offer sdp: Unknown transceiver
```

This is the diff between the local SDP before calling `createOffer()` and the one given by `createOffer()`:

```diff
@@ -1,8 +1,8 @@
 v=0
-o=- 2568895024905517701 5 IN IP4 127.0.0.1
+o=- 2568895024905517701 6 IN IP4 127.0.0.1
 s=-
 t=0 0
-a=group:BUNDLE 0 1 2
+a=group:BUNDLE 0 1
 a=msid-semantic: WMS 4b887cad-36bc-43a7-bc11-b1d7b43b3e4d
 m=audio 54719 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
 c=IN IP4 192.168.1.34
@@ -52,7 +52,7 @@
 a=mid:1
 a=sctp-port:5000
 a=max-message-size:262144
-m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 118 114 115 116
+m=video 0 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 124 119 123 118 114 115 116
 c=IN IP4 0.0.0.0
 a=rtcp:9 IN IP4 0.0.0.0
 a=ice-ufrag:Grj8
@@ -61,19 +61,7 @@
 a=fingerprint:sha-256 FB:37:7F:C7:03:C9:4E:6E:6F:E6:3F:F2:AB:8E:10:A9:68:49:A5:EB:58:BB:21:14:3E:FA:ED:7F:51:A7:B4:C9
 a=setup:actpass
 a=mid:2
-a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
-a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
-a=extmap:13 urn:3gpp:video-orientation
-a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
-a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
-a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
-a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
-a=extmap:8 http://www.webrtc.org/experiments/rtp-hdrext/color-space
-a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
-a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
-a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
-a=sendonly
-a=msid:4b887cad-36bc-43a7-bc11-b1d7b43b3e4d e66bb93c-1fb4-49f8-bcaa-639b243c2ca9
+a=inactive
 a=rtcp-mux
 a=rtcp-rsize
 a=rtpmap:96 VP8/90000
@@ -160,7 +148,3 @@
 a=rtpmap:115 rtx/90000
 a=fmtp:115 apt=114
 a=rtpmap:116 ulpfec/90000
-a=rid:r0 send
-a=rid:r1 send
-a=rid:r2 send
-a=simulcast:send r0;r1;r2
```

Everything looks right.

**Comment by ArmorDarks** [comment] 2020-11-20 15:26
@ibc Note that your reproduction error happens in `setLocalDescription`, but the issue is about `createOffer` stage, which happens earlier. It puzzles even more because it's unclear how a peer can create own offer and say that he doesn't know what those transceivers are.

The issue started to happen about a few months ago in Canary. [Chrome 87](https://chromium.googlesource.com/chromium/src/+log/86.0.4240.93..87.0.4280.60?pretty=fuller&n=10000) contains quite a lot of changes and fixes, related to the receivers and transceivers stopping. Maybe in the mediasoup client they are not stopped properly before the re-negotiation?

**Comment by ibc** [comment] 2020-11-20 15:29
The rule is easy: If `pc.createOffer()` generates an offer that later fails when applied into `pc.setLocalDescription(offer)`, then the issue is in Chrome/libwebrtc. No doubts about this.

**Comment by ArmorDarks** [comment] 2020-11-20 15:37
It actually can't generate offer in the first place, so I'm not sure it applies here. I was quite surprised when saw that you were able to reach `setLocalDescription` stage :)

So, it's either indeed a Chromium bug, or maybe the current peer connection state is wrong, so it can't gather the offer.

**Comment by ibc** [comment] 2020-11-20 15:38
> It actually can't generate offer in the first place

It does generate the offer. `pc.createOffer()` does work as I pasted above.

**Comment by ArmorDarks** [comment] 2020-11-20 15:45
Hm, that's odd. In my case (and see @geongun20 and @newsiberian) it fails on the creation stage.

For me the reproduction is the same:

1. Start webcam with `getUserMedia`
2. Start another stream, for instance, screen sharing with `getDisplayMedia`
3. Stop screen sharing producer
4. Start screen sharing again
5. It will result in the mentioned `createOffer` error

For some very odd reason, I can't reproduce it on the localhost. Only on the production server.

**Comment by newsiberian** [comment] 2020-11-20 15:53
Yup, in our case we are stopping/starting producer instead of pause/resume it each time when user turn on/off mic/cam that's why I said before that our reproduction case is to turn on/of cam/mic several times. And Iñaki, sorry for mentioning you :sweat_smile:

**Comment by ibc** [comment] 2020-11-20 16:05
I don't want to go to higher levels. The issue is clearly reproducible with my steps above and the error is in `pc.setLocalDescription()` (there may be more, but this is clear) so this is a regression in Chrome/libwebrtc.

I know that it's easier to report issues here than in Chroimum/libwebrtc trackers since there they require a jsfiddle that reproduces the error and they don't want to know anything about higher layers (such as mediasoup-client library). If I have time next week I'll try to make a jsfiddle reproducing the bug by just using PeerConnections. If anyone can help on this, that would be great, but this is not a bug in mediasoup-client. I'll keep this issue open for updates.

**Comment by amiznikov** [comment] 2020-11-20 16:37
I faced with same problem. As far as I know that problem is being reproduced by 
re-creation producer. If user click on button mic  producer will pause/resume  
in default demo but in my app I changed it onto disable/enable method what make broken opportunity using webcam/mic. I've found solution when I switch off mic or webcam I don't stop/pause producer I stop media track which related with producer. If webcam/mic has to switch on I create new media track and replace it in current producer.

**Comment by ArmorDarks** [comment] 2020-11-20 19:39
@ibc Here is my attempt to reproduce the issue https://jsfiddle.net/ArmorDarks/0635awsx/115/. However, it works fine

How to use:

1. Open the same URL in two tabs
2. Click connect in the first tab
3. Click start screen sharing
4. Stop screen sharing
5. It is expected to see `setLocalDescription` error in `chrome://webrtc-internals/`, but it doesn't happen

My assumption that it doesn't happen because my code does not modifies SDP. However, here https://jsfiddle.net/ArmorDarks/0635awsx/115/ media section is modified. Didn't figure out does it affect Chrome 87 yet, though.

**Comment by dimes** [comment] 2020-11-20 23:56
Is it possible that this issue is caused by reusing `m=` sections? https://github.com/versatica/mediasoup-client/commit/c0da3089167440e53c57c87f8f235bcdd5f2bd8f

**Comment by ibc** [comment] 2020-11-20 23:59
Hi, guys, you can insist in blaming mediasoup-client. I'll say this for third and last time:

**If `pc.createOffer()` does work and it generates an offer that later fails when applied into `pc.setLocalDescription(offer)`, then this is an issue is in Chrome/libwebrtc. Period.**

**Comment by nazar-pc** [comment] 2020-11-21 00:03
Right, I think no one is arguing with that, rather we are looking for what Chrome/libwebrtc doesn't like about the way mediasoup-client uses browser APIs and maybe work around that while it is not fixed upstream.

BTW I have spent over an hour on reduced test case and wasn't able to come up with one yet.

**Comment by newsiberian** [comment] 2020-11-21 04:57
In our case its never reach this line `await this._pc.setLocalDescription(offer);`

![Peek 2020-11-21 11-54](https://user-images.githubusercontent.com/11130487/99867926-8f39b000-2bf0-11eb-9f83-6fd048df304f.gif)

hope this makes things clearer

**Comment by nazar-pc** [comment] 2020-11-21 05:00
@newsiberian that also happens to me, but only after the first `setLocalDescription()` call failure that can be found with red background on `chrome://webrtc-internals` page.

**Comment by ArmorDarks** [comment] 2020-11-21 10:00
Made more tests, and it seems that Chrome 87 after all doesn't like what `mediaSection.close` does:

https://github.com/versatica/mediasoup-client/blob/871f61b5e23d6a2c96728041ff28544535f2e443/src/handlers/sdp/RemoteSdp.ts#L285-L313

If we disable complete closing of the media section and allow only disabling, it solves the issue with Chrome 87:

```diff
closeMediaSection(mid: string): void
{
-  const idx = this._midToIndex.get(mid);

-  if (idx === undefined)
-  {
-    throw new Error(`no media section found with mid '${mid}'`);
-  }

-  const mediaSection = this._mediaSections[idx];

  // NOTE: Closing the first m section is a pain since it invalidates the
  // bundled transport, so let's avoid it.
-  if (mid === this._firstMid)
-  {
     logger.debug(
       'closeMediaSection() | cannot close first media section, disabling it instead [mid:%s]',
       mid);

     this.disableMediaSection(mid);

     return;
-  }

-  mediaSection.close();

-  // Regenerate BUNDLE mids.
-  this._regenerateBundleMids();
}
```

@ibc Is it an adequate workaround for now, for Chrome 87 only? If I'm not mistaken, the only side-effect is that SDP will be never cleared, but it's better than a broken removal of the producers. If yes, we'll just make a temporary fork.

I remember @nazar-pc mentioned that in Chromium 88 Nightly he can't reproduce the issue. Probably that's a regression that was already addressed, which means we just need a temporary workaround until 88 will be released.

As I side note, I'm not sure that 87 behavior is actually incorrect. `mediaSection.close()` removes a section from the SDP, but _transiever actually continues to exist_ (not sure there's a way to fully close its receiver part in Chrome), so it feels like Chrome 87 was just more pedantic about the fact that it exists but unexpectedly absent in the SDP.

**Comment by fippo** [comment] 2020-11-21 10:38
Is this gone in Chrome 88/89? Then this was already fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=1134686 but possibly not merged.

**Comment by ibc** [comment] 2020-11-21 10:51
> Is this gone in Chrome 88/89? Then this was already fixed in https://bugs.chromium.org/p/chromium/issues/detail?id=1134686 but possibly not merged.

Exactly:

> This fixes the case where a media section is rejected in an answer,
something that is done by SFUs, but not possible using transceiver.stop().

We close transceivers my rejecting the remote m= section with port 0, which is perfectly valid.

BTW closing a media section in mediasoup-client does not mean that the m section is removed from the remote SDP (that would be invalid). This is in response to a recent comment above.

Thanks @fippo

**Comment by ArmorDarks** [comment] 2020-11-21 10:59
> BTW closing a media section in mediasoup-client does not mean that the m section is removed from the remote SDP (that would be invalid). This is in response to a recent comment above.

Got it, thanks. Though, just `mediaSection.disable()` seems to be ok for 87, but `mediaSection.close()` - isn't. Is it okay to `disable` sections for version 87, as a temporary workaround, until 88 release?

**Comment by ibc** [comment] 2020-11-21 11:04
> Is it okay to `disable` sections for version 87, as a temporary workaround, until 88 release?

This would be about adding an exception for M87 (I'm not gonna stop closing media sections because it would leak as demonstrated when it was not done). This means work for me due to a bug in Chrome and I'm pretty busy with other priorities. Things that may change my priorities are relevant donations to the project

**Comment by ArmorDarks** [comment] 2020-11-21 11:19
@ibc Thanks for the input! Of course, I do not expect you to invest time in this. I wanted to ensure whether doing this in a temporary fork is a good idea or not.

**Comment by andrewlin12** [comment] 2020-11-21 16:06
@ArmorDarks - I tried your workaround and it does avoid the error, but the offer size increases whenever you publish another stream. I worked around it by creating a new transport for each new track that is published.

**Comment by amiznikov** [comment] 2020-11-23 13:24
that looks like a reason of problem

https://groups.google.com/g/discuss-webrtc/c/6VmKkCjRK0k/m/YyOTQyQ5AAAJ


Stopping transceivers
Transceivers now have a new function called “stop”. Once called, all usage of that transceiver for sending and receiving will cease, and an offer/answer cycle will remove it from the list of transceivers.
The media section in SDP can then be reused for other purposes. See the spec for more information.
This feature is available behind a flag in M87, and will be generally available in M88.

**Comment by ibc** [comment] 2020-11-23 13:36
The fact that transceiver.stop() finally exists is not the problem. The problem is indicated in a comment above, and it's due to a bug in libwebrtc already fixed in M88.

**Comment by ibc** [comment] 2020-11-24 14:54
Ok, confirmed that:

- This is a bug in libwebrtc/Chrome and not in mediasoup-client (even if easier to report everything to mediasoup project because we don't request jsfiddles).
- The issue does not happen in Chrome 88 or 89 (Canary).
- According to the [issue in libwebrtc](https://bugs.chromium.org/p/chromium/issues/detail?id=1134686#c13) they are gonna fix M87 soon.

So closing. Nothing to do in mediasoup-client side.

**Closed as completed by ibc** 2020-11-24 14:54 UTC
Labels: bug
